
services:
  frontend:
    build: ./client
    expose:
      - "3000"
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      VITE_API_URL: http://backend:4000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`beekeepers.community`)"
      - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"

  backend:
    build: ./server
    expose:
      - "4000"
    environment:
      MONGODB_URI: "${MONGODB_URI?}"
      JWT_SECRET: rxRkSCngw2mOZUeUWAT1d4KMNKBSRpv3
      NODE_ENV: production
      FRONTEND_URL: http://frontend:3000

networks:
  default:
    name: proxy
    external: true


