
services:
  frontend:
    build: ./client
    expose:
      - "3000"
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      VITE_API_URL: http://backend:4000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`beekeepers.community`)"
      - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"

  backend:
    build: ./server
    expose:
      - "4000"
    environment:
      MONGODB_URI: "${MONGODB_URI?}"
      MAILGUN_API_KEY: "${MAILGUN_API_KEY?}"
      EMAIL_FROM: "Beekeepers <noreply@mail.beekeepers.community>"
      JWT_SECRET: "${JWT_SECRET?}"
      GOOGLE_CALLBACK_URL: "${GOOGLE_CALLBACK_URL?}"
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID?}"
      GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET?}"
      MAILGUN_DOMAIN: "${MAILGUN_DOMAIN?}"
      NODE_ENV: production
      FRONTEND_URL: http://frontend:3000

networks:
  default:
    name: proxy
    external: true

