
services:
  frontend:
    build: ./client
    expose:
      - "3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://backend:4000

  backend:
    build: ./server
    expose:
      - "4000"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/beekeepers
      JWT_SECRET: rxRkSCngw2mOZUeUWAT1d4KMNKBSRpv3
      NODE_ENV: production
      FRONTEND_URL: http://frontend:3000

networks:
  default:
    name: proxy
    external: true

