name: Deploy to Production on Master Push

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Remote Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker CLI
        uses: docker/setup-docker-action@v4

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Configure DOCKER_HOST and Add Remote Host to Known Hosts
        env:
          REMOTE_DOCKER_USER: deployer
          REMOTE_DOCKER_HOST_IP: beekeepers.community
        run: |
          echo "Setting DOCKER_HOST to ssh://${REMOTE_DOCKER_USER}@${REMOTE_DOCKER_HOST_IP}"
          echo "DOCKER_HOST=ssh://${REMOTE_DOCKER_USER}@${REMOTE_DOCKER_HOST_IP}" >> $GITHUB_ENV
          
          echo "Adding remote host to known_hosts"
          mkdir -p ~/.ssh
          ssh-keyscan -H "${REMOTE_DOCKER_HOST_IP}" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          
          echo "Verifying Docker connection to remote host..."
          docker version
          docker context ls
      - name: Run Deployment
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: make deploy 

